### ISSUE TITLE
如何在前端中显示公式

### ISSUE THREAD

**Issue by RayShark** [Dustyposa/rasa_bot_front#1]
我现在从rasa返回的回答是这个样子的：
`"<img class="mathml" src="http://math.21cnjy.com/MathMLToImage?mml=%3Cmath+xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F1998%2FMath%2FMathML%22%3E%3Cmrow%3E%3Cmn%3E1%3C%2Fmn%3E%3Cmo%3E%E2%88%92%3C%2Fmo%3E%3Cmfrac%3E%3Cmn%3E1%3C%2Fmn%3E%3Cmi%3Ex%3C%2Fmi%3E%3C%2Fmfrac%3E%3C%2Fmrow%3E%3C%2Fmath%3E&key=14fdf09267c6c3d27d9149c380c1d353" style="vertical-align: middle;" />"`
数据库里存的都是html格式的公式，
希望在前端的消息框里能显示成：

A: <img class="mathml" src="http://math.21cnjy.com/MathMLToImage?mml=%3Cmath+xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F1998%2FMath%2FMathML%22%3E%3Cmrow%3E%3Cmn%3E1%3C%2Fmn%3E%3Cmo%3E%E2%88%92%3C%2Fmo%3E%3Cmfrac%3E%3Cmn%3E1%3C%2Fmn%3E%3Cmi%3Ex%3C%2Fmi%3E%3C%2Fmfrac%3E%3C%2Fmrow%3E%3C%2Fmath%3E&key=14fdf09267c6c3d27d9149c380c1d353" style="vertical-align: middle;" />
这种格式吗？

分两条回复发，一条回复A：，一条回复图片格式的公式这样应该是可以的。
-- A：
-- ![image](https://user-images.githubusercontent.com/26996377/133560416-0c34c198-bae6-4e4a-9694-f093e8c64fed.png)
现在就是想请教一下大神如何在一条消息框里回复选项+公式呢。您这边有处理过类似的问题吗？

**Comment by Dustyposa** [comment]
这个你要自己处理button了，把 button 里面的文字用图片替换。或者数据库存成 `latex` 格式，前端渲染

**Comment by RayShark** [comment]
ok，明白，我这边正好有一套公式图片转latex的工具，试一下把数据库里的都存成latex格式。
感谢！
