### ISSUE TITLE
请教一下如何在前端简单实现调用麦克风录音

### ISSUE THREAD

**Issue by RayShark** [Dustyposa/rasa_bot_front#2]
大佬，我对React不是很熟悉，请问你有了解过怎么在React框架下调用麦克风完成录音吗？
我在网上搜了好多都没有类似的，可否给一点思路上的提示？比如哪个组件能实现。。

**Comment by Dustyposa** [comment]
你搜索的关键词错了。 语音输入只和 `js` 有关系。
我用了一个 `UI` 框架，可以参考这个框架的[文档](https://chatui.io/sdk/recorder)。

**Comment by RayShark** [comment]
原来是这样，我说怎么找不到，感谢大佬，我去研究一下~
